"""GPT-OSS source generation for all-layers-in-one-graph decode kernel."""

from __future__ import annotations


def generate_full_decode_kernel_source(
    *,
    token_bucket: int,
    attn_bucket: int,
    num_hidden_layers: int,
    num_heads: int,
    num_kv_heads: int,
    head_dim: int,
    rms_norm_eps: float,
    experts_per_token: int,
    tp_degree: int,
    ep_degree: int,
    ep_rank: int,
    local_num_experts: int,
    vocab_start_index: int,
    vocab_end_index: int,
    tp_replica_groups: tuple[tuple[int, ...], ...],
    ep_replica_groups: tuple[tuple[int, ...], ...],
) -> str:
    """Generate a no-SP decode graph with embedding + all layers.

    Outputs hidden states; LM head runs separately via LogitsProcessor.
    """
    softmax_scale = 1.0 / (float(head_dim) ** 0.5)

    params: list[str] = [
        "input_ids",
        "embeddings",
        "cos",
        "sin",
        "slot_mapping",
        "p_tqi",
        "p_tbt",
        "p_tm",
        "p_ndls",
        "p_qup",
        "p_lti",
        "d_tqi",
        "d_tbt",
        "d_tm",
        "d_ndls",
        "d_qup",
        "d_lti",
    ]
    for layer_idx in range(num_hidden_layers):
        params.extend(
            [
                f"kv_cache_L{layer_idx}",
                f"input_norm_L{layer_idx}",
                f"w_q_L{layer_idx}",
                f"w_k_L{layer_idx}",
                f"w_v_L{layer_idx}",
                f"b_q_L{layer_idx}",
                f"b_k_L{layer_idx}",
                f"b_v_L{layer_idx}",
                f"sink_L{layer_idx}",
                f"w_o_L{layer_idx}",
                f"b_o_L{layer_idx}",
                f"post_attn_norm_L{layer_idx}",
                f"router_w_L{layer_idx}",
                f"router_b_L{layer_idx}",
                f"gup_w_L{layer_idx}",
                f"gup_bias_L{layer_idx}",
                f"down_w_L{layer_idx}",
                f"down_bias_bc_L{layer_idx}",
            ]
        )

    group_calls: list[str] = []
    for layer_base in range(0, num_hidden_layers, 4):
        group_args = [
            "hidden",
            "cos",
            "sin",
            "slot_mapping",
            "p_tqi",
            "p_tbt",
            "p_tm",
            "p_ndls",
            "p_qup",
            "p_lti",
            "d_tqi",
            "d_tbt",
            "d_tm",
            "d_ndls",
            "d_qup",
            "d_lti",
        ]
        for layer_idx in range(layer_base, layer_base + 4):
            group_args.extend(
                [
                    f"kv_cache_L{layer_idx}",
                    f"input_norm_L{layer_idx}",
                    f"w_q_L{layer_idx}",
                    f"w_k_L{layer_idx}",
                    f"w_v_L{layer_idx}",
                    f"b_q_L{layer_idx}",
                    f"b_k_L{layer_idx}",
                    f"b_v_L{layer_idx}",
                    f"sink_L{layer_idx}",
                    f"w_o_L{layer_idx}",
                    f"b_o_L{layer_idx}",
                    f"post_attn_norm_L{layer_idx}",
                    f"router_w_L{layer_idx}",
                    f"router_b_L{layer_idx}",
                    f"gup_w_L{layer_idx}",
                    f"gup_bias_L{layer_idx}",
                    f"down_w_L{layer_idx}",
                    f"down_bias_bc_L{layer_idx}",
                ]
            )
        group_calls.append(
            "    hidden = decode_group4_nki_no_sp_fn(\n"
            + "".join(f"        {arg},\n" for arg in group_args)
            + "        token_bucket=_TOKEN_BUCKET,\n"
            + "        attn_bucket=_ATTN_BUCKET,\n"
            + "        num_heads=_NUM_HEADS,\n"
            + "        num_kv_heads=_NUM_KV_HEADS,\n"
            + "        head_dim=_HEAD_DIM,\n"
            + "        rms_norm_eps=_RMS_NORM_EPS,\n"
            + "        softmax_scale=_SOFTMAX_SCALE,\n"
            + "        top_k=_TOP_K,\n"
            + "        tp_degree=_TP_DEGREE,\n"
            + "        ep_degree=_EP_DEGREE,\n"
            + "        ep_rank=_EP_RANK,\n"
            + "        local_num_experts=_LOCAL_NUM_EXPERTS,\n"
            + "        ep_replica_groups=_EP_REPLICA_GROUPS,\n"
            + "        tp_replica_groups=_TP_REPLICA_GROUPS,\n"
            + "    )\n"
        )

    lm_block = (
        "    _HIDDEN_DTYPE = embeddings.dtype\n"
        "    hidden_out = hidden.astype(np.float32)\n"
        "    hidden_out = hidden_out.astype(_HIDDEN_DTYPE)\n"
        "    hidden_aux = np.copy(hidden_out)\n"
        "    return hidden_out, hidden_aux\n"
    )

    src = f"""# AUTO-GENERATED. DO NOT EDIT.
# Generated by GptOssExecutor for decode-graph mode.

from __future__ import annotations

import numpy as np

from nkipy_serving.models.gpt_oss import decode_group4_nki_no_sp_fn
from nkipy_serving.ops.vocab_parallel_embedding import vocab_parallel_embedding_no_sp_fn


def gpt_oss_full_decode_embed_layers_local_forward_t{int(token_bucket)}_tp{int(tp_degree)}_ep{int(ep_degree)}(
    {", ".join(params)},
):
    _TOKEN_BUCKET = {int(token_bucket)}
    _ATTN_BUCKET = {int(attn_bucket)}
    _NUM_HEADS = {int(num_heads)}
    _NUM_KV_HEADS = {int(num_kv_heads)}
    _HEAD_DIM = {int(head_dim)}
    _RMS_NORM_EPS = {float(rms_norm_eps)}
    _SOFTMAX_SCALE = {float(softmax_scale)}
    _TOP_K = {int(experts_per_token)}
    _TP_DEGREE = {int(tp_degree)}
    _EP_DEGREE = {int(ep_degree)}
    _EP_RANK = {int(ep_rank)}
    _LOCAL_NUM_EXPERTS = {int(local_num_experts)}
    _VOCAB_START_INDEX = {int(vocab_start_index)}
    _VOCAB_END_INDEX = {int(vocab_end_index)}
    _TP_REPLICA_GROUPS = {repr(tp_replica_groups)}
    _EP_REPLICA_GROUPS = {repr(ep_replica_groups)}

    hidden = vocab_parallel_embedding_no_sp_fn(
        input_ids,
        embeddings,
        vocab_start_index=_VOCAB_START_INDEX,
        vocab_end_index=_VOCAB_END_INDEX,
        tp_degree=_TP_DEGREE,
        tp_replica_groups=_TP_REPLICA_GROUPS,
    )

{"".join(group_calls)}
{lm_block}
"""
    return src
