"""Qwen3-MoE source generation for all-layers-in-one-graph decode kernel."""

from __future__ import annotations


def generate_full_decode_kernel_source(
    *,
    token_bucket: int,
    attn_bucket: int,
    num_hidden_layers: int,
    num_heads: int,
    num_kv_heads: int,
    head_dim: int,
    rms_norm_eps: float,
    softmax_scale: float,
    experts_per_token: int,
    tp_degree: int,
    ep_degree: int,
    ep_rank: int,
    local_num_experts: int,
    tp_replica_groups: tuple[tuple[int, ...], ...],
    ep_replica_groups: tuple[tuple[int, ...], ...],
) -> str:
    """Generate Python source for all-layers-in-one-graph decode (no SP)."""
    num_layers = int(num_hidden_layers)

    # Parameters: hidden + cos + sin + slot_mapping + tile plans + per-layer weights.
    params: list[str] = [
        "hidden",
        "cos",
        "sin",
        "slot_mapping",
        "p_tqi",
        "p_tbt",
        "p_tm",
        "p_ndls",
        "p_qup",
        "p_lti",
        "d_tqi",
        "d_tbt",
        "d_tm",
        "d_ndls",
        "d_qup",
        "d_lti",
    ]
    for layer_idx in range(num_layers):
        params.extend(
            [
                f"kv_cache_L{layer_idx}",
                f"input_norm_L{layer_idx}",
                f"w_q_L{layer_idx}",
                f"w_k_L{layer_idx}",
                f"w_v_L{layer_idx}",
                f"q_norm_L{layer_idx}",
                f"k_norm_L{layer_idx}",
                f"w_o_L{layer_idx}",
                f"post_attn_norm_L{layer_idx}",
                f"router_w_L{layer_idx}",
                f"gup_w_L{layer_idx}",
                f"gup_bias_L{layer_idx}",
                f"down_w_L{layer_idx}",
                f"down_bias_bc_L{layer_idx}",
            ]
        )

    # Generate per-layer decode_layer_nki_no_sp_fn calls.
    layer_calls: list[str] = []
    for layer_idx in range(num_layers):
        layer_args = [
            "hidden",
            "cos",
            "sin",
            "slot_mapping",
            "p_tqi",
            "p_tbt",
            "p_tm",
            "p_ndls",
            "p_qup",
            "p_lti",
            "d_tqi",
            "d_tbt",
            "d_tm",
            "d_ndls",
            "d_qup",
            "d_lti",
            f"kv_cache_L{layer_idx}",
            f"input_norm_L{layer_idx}",
            f"w_q_L{layer_idx}",
            f"w_k_L{layer_idx}",
            f"w_v_L{layer_idx}",
            f"q_norm_L{layer_idx}",
            f"k_norm_L{layer_idx}",
            f"w_o_L{layer_idx}",
            f"post_attn_norm_L{layer_idx}",
            f"router_w_L{layer_idx}",
            f"gup_w_L{layer_idx}",
            f"gup_bias_L{layer_idx}",
            f"down_w_L{layer_idx}",
            f"down_bias_bc_L{layer_idx}",
        ]
        layer_calls.append(
            "    hidden = decode_layer_nki_no_sp_fn(\n"
            + "".join(f"        {arg},\n" for arg in layer_args)
            + "        token_bucket=_TOKEN_BUCKET,\n"
            + "        attn_bucket=_ATTN_BUCKET,\n"
            + "        num_heads=_NUM_HEADS,\n"
            + "        num_kv_heads=_NUM_KV_HEADS,\n"
            + "        head_dim=_HEAD_DIM,\n"
            + "        rms_norm_eps=_RMS_NORM_EPS,\n"
            + "        softmax_scale=_SOFTMAX_SCALE,\n"
            + "        top_k=_TOP_K,\n"
            + "        tp_degree=_TP_DEGREE,\n"
            + "        ep_degree=_EP_DEGREE,\n"
            + "        ep_rank=_EP_RANK,\n"
            + "        local_num_experts=_LOCAL_NUM_EXPERTS,\n"
            + "        ep_replica_groups=_EP_REPLICA_GROUPS,\n"
            + "        tp_replica_groups=_TP_REPLICA_GROUPS,\n"
            + "    )\n"
        )

    lm_block = (
        "    _HIDDEN_DTYPE = hidden.dtype\n"
        "    hidden_out = hidden.astype(np.float32)\n"
        "    hidden_out = hidden_out.astype(_HIDDEN_DTYPE)\n"
        "    hidden_aux = np.copy(hidden_out)\n"
        "    return hidden_out, hidden_aux\n"
    )

    src = f"""# AUTO-GENERATED. DO NOT EDIT.
# Generated by Qwen3MoeExecutor for decode-graph mode.

from __future__ import annotations

import numpy as np

from nkipy_serving.models.qwen3_moe import decode_layer_nki_no_sp_fn


def qwen3_moe_full_decode_layers_forward_t{int(token_bucket)}_tp{int(tp_degree)}_ep{int(ep_degree)}(
    {", ".join(params)},
):
    _TOKEN_BUCKET = {int(token_bucket)}
    _ATTN_BUCKET = {int(attn_bucket)}
    _NUM_HEADS = {int(num_heads)}
    _NUM_KV_HEADS = {int(num_kv_heads)}
    _HEAD_DIM = {int(head_dim)}
    _RMS_NORM_EPS = {float(rms_norm_eps)}
    _SOFTMAX_SCALE = {float(softmax_scale)}
    _TOP_K = {int(experts_per_token)}
    _TP_DEGREE = {int(tp_degree)}
    _EP_DEGREE = {int(ep_degree)}
    _EP_RANK = {int(ep_rank)}
    _LOCAL_NUM_EXPERTS = {int(local_num_experts)}
    _TP_REPLICA_GROUPS = {repr(tp_replica_groups)}
    _EP_REPLICA_GROUPS = {repr(ep_replica_groups)}

{"".join(layer_calls)}
{lm_block}
"""
    return src
