"""Qwen3-dense source generation for all-layers-in-one-graph kernel."""

from __future__ import annotations


def generate_full_kernel_source(
    *,
    token_bucket: int,
    attn_bucket: int,
    num_hidden_layers: int,
    num_heads: int,
    num_kv_heads: int,
    head_dim: int,
    rms_norm_eps: float,
    tp_degree: int,
) -> str:
    """Generate Python source for the fused transformer-layers kernel.

    Outputs hidden states; LM head (topk or sampling) runs separately.
    """
    softmax_scale = 1.0 / (float(head_dim) ** 0.5)

    # Parameter list (arrays only) in compile_and_load positional order.
    params: list[str] = [
        "hidden",
        "cos",
        "sin",
        "slot_mapping",
        "p_tqi",
        "p_tbt",
        "p_tm",
        "p_ndls",
        "p_qup",
        "p_lti",
        "d_tqi",
        "d_tbt",
        "d_tm",
        "d_ndls",
        "d_qup",
        "d_lti",
    ]
    for layer_idx in range(num_hidden_layers):
        params.extend(
            [
                f"kv_cache_L{layer_idx}",
                f"input_norm_L{layer_idx}",
                f"w_q_L{layer_idx}",
                f"w_k_L{layer_idx}",
                f"w_v_L{layer_idx}",
                f"q_norm_L{layer_idx}",
                f"k_norm_L{layer_idx}",
                f"w_o_L{layer_idx}",
                f"post_attn_norm_L{layer_idx}",
                f"w_gate_L{layer_idx}",
                f"w_up_L{layer_idx}",
                f"w_down_L{layer_idx}",
            ]
        )

    layer_tuples: list[str] = []
    for layer_idx in range(num_hidden_layers):
        layer_tuples.append(
            "("
            + ", ".join(
                [
                    f"kv_cache_L{layer_idx}",
                    f"input_norm_L{layer_idx}",
                    f"w_q_L{layer_idx}",
                    f"w_k_L{layer_idx}",
                    f"w_v_L{layer_idx}",
                    f"q_norm_L{layer_idx}",
                    f"k_norm_L{layer_idx}",
                    f"w_o_L{layer_idx}",
                    f"post_attn_norm_L{layer_idx}",
                    f"w_gate_L{layer_idx}",
                    f"w_up_L{layer_idx}",
                    f"w_down_L{layer_idx}",
                ]
            )
            + ")"
        )

    src = f"""# AUTO-GENERATED. DO NOT EDIT.
# Generated by Qwen3DenseExecutor for full-graph mode.
# Outputs hidden states -- LM head (topk or sampling) runs separately.

import numpy as np

from nkipy_serving.attention.nki_blocksparse_flash_attention import (
    nki_attention_unified,
    nki_update_kv_cache_core,
)
from nkipy_serving.models.qwen3_dense import (
    post_attn_fn,
    pre_attn_fn,
)


def qwen3_dense_full_forward_t{token_bucket}_tp{tp_degree}(
    {", ".join(params)},
):
    _TOKEN_BUCKET = {int(token_bucket)}
    _ATTN_BUCKET = {int(attn_bucket)}
    _NUM_HEADS = {int(num_heads)}
    _NUM_KV_HEADS = {int(num_kv_heads)}
    _HEAD_DIM = {int(head_dim)}
    _RMS_NORM_EPS = {float(rms_norm_eps)}
    _TP_DEGREE = {int(tp_degree)}
    _SOFTMAX_SCALE = {float(softmax_scale)}

    layers = [
        {", ".join(layer_tuples)}
    ]

    for (
        kv_cache,
        input_norm,
        w_q,
        w_k,
        w_v,
        q_norm,
        k_norm,
        w_o,
        post_attn_norm,
        w_gate,
        w_up,
        w_down,
    ) in layers:
        q, k, v = pre_attn_fn(
            hidden,
            input_norm=input_norm,
            w_q=w_q,
            w_k=w_k,
            w_v=w_v,
            q_norm=q_norm,
            k_norm=k_norm,
            cos=cos,
            sin=sin,
            num_heads=_NUM_HEADS,
            num_kv_heads=_NUM_KV_HEADS,
            head_dim=_HEAD_DIM,
            rms_norm_eps=_RMS_NORM_EPS,
        )

        kv_cache = nki_update_kv_cache_core(k, v, kv_cache, slot_mapping)

        if _ATTN_BUCKET > _TOKEN_BUCKET:
            pad_t = _ATTN_BUCKET - _TOKEN_BUCKET
            from nkipy.core.tensor_apis import zeros
            q_pad = zeros((pad_t, _NUM_HEADS, _HEAD_DIM), dtype=q.dtype)
            k_pad = zeros((pad_t, _NUM_KV_HEADS, _HEAD_DIM), dtype=k.dtype)
            v_pad = zeros((pad_t, _NUM_KV_HEADS, _HEAD_DIM), dtype=v.dtype)
            q_attn = np.concatenate((q, q_pad), axis=0)
            k_attn = np.concatenate((k, k_pad), axis=0)
            v_attn = np.concatenate((v, v_pad), axis=0)
        else:
            q_attn, k_attn, v_attn = q, k, v

        context_attn = nki_attention_unified(
            q_attn,
            k_attn,
            v_attn,
            kv_cache,
            p_tqi,
            p_tbt,
            p_tm,
            p_ndls,
            p_qup,
            p_lti,
            d_tqi,
            d_tbt,
            d_tm,
            d_ndls,
            d_qup,
            d_lti,
            softmax_scale=_SOFTMAX_SCALE,
        )
        context = (
            context_attn[:_TOKEN_BUCKET] if _ATTN_BUCKET > _TOKEN_BUCKET else context_attn
        )

        hidden = post_attn_fn(
            hidden,
            context=context,
            w_o=w_o,
            post_attn_norm=post_attn_norm,
            w_gate=w_gate,
            w_up=w_up,
            w_down=w_down,
            num_heads=_NUM_HEADS,
            head_dim=_HEAD_DIM,
            rms_norm_eps=_RMS_NORM_EPS,
            tp_degree=_TP_DEGREE,
        )

    return hidden
"""
    return src
